# Generated by Django 4.2.7 on 2023-11-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kinodb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sorteo', models.IntegerField()),
                ('fecha', models.DateField()),
                ('number1', models.PositiveSmallIntegerField()),
                ('number2', models.PositiveSmallIntegerField()),
                ('number3', models.PositiveSmallIntegerField()),
                ('number4', models.PositiveSmallIntegerField()),
                ('number5', models.PositiveSmallIntegerField()),
                ('number6', models.PositiveSmallIntegerField()),
                ('number7', models.PositiveSmallIntegerField()),
                ('number8', models.PositiveSmallIntegerField()),
                ('number9', models.PositiveSmallIntegerField()),
                ('number10', models.PositiveSmallIntegerField()),
                ('number11', models.PositiveSmallIntegerField()),
                ('number12', models.PositiveSmallIntegerField()),
                ('number13', models.PositiveSmallIntegerField()),
                ('number14', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
