# Generated by Django 4.2.7 on 2023-12-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoprincipal', '0002_chanchitodb_chao1db_chao2db_chao3db_combodb_rekinodb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivosxl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excels')),
            ],
        ),
    ]
