# Generated by Django 4.2.7 on 2023-12-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoprincipal', '0003_archivosxl'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanchitodb',
            name='num_ganadores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chao1db',
            name='num_ganadores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chao2db',
            name='num_ganadores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chao3db',
            name='num_ganadores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combodb',
            name='num_ganadores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kinodb',
            name='num_ganadores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rekinodb',
            name='num_ganadores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
