# Generated by Django 4.2.7 on 2023-12-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoprincipal', '0004_chanchitodb_num_ganadores_chao1db_num_ganadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanchitodb',
            name='tipo_ingreso',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='chao1db',
            name='tipo_ingreso',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='chao2db',
            name='tipo_ingreso',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='chao3db',
            name='tipo_ingreso',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='combodb',
            name='tipo_ingreso',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='kinodb',
            name='tipo_ingreso',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='rekinodb',
            name='tipo_ingreso',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
